import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "fs";
import path from "path";
import os from "os";
import { emit, emitDry } from "../src/core/emitter.js";
import type { BlogPost, ResolvedConfig } from "../src/types.js";

function makeConfig(overrides: Partial<ResolvedConfig> = {}): ResolvedConfig {
  return {
    content: "content",
    output: "blog.generated.ts",
    format: "ts",
    categories: [],
    featured: undefined,
    strict: false,
    ...overrides,
  };
}

const samplePosts: BlogPost[] = [
  {
    slug: "hello-world",
    title: "Hello World",
    excerpt: "A short intro.",
    category: "Engineering",
    tags: ["open-source", "markdown"],
    author: "Test Author",
    date: "2026-01-15",
    readTime: "3 min read",
    featured: true,
    draft: false,
    order: 0,
  },
  {
    slug: "getting-started",
    title: "Getting Started",
    excerpt: "Get up and running fast.",
    category: "Tutorial",
    tags: ["tutorial"],
    author: "Test Author",
    date: "2026-02-20",
    readTime: "5 min read",
    featured: false,
    draft: true,
    order: 0,
  },
];

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "mdpublish-test-"));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

describe("emitDry (TypeScript format)", () => {
  it("includes the BlogPost interface", () => {
    const output = emitDry(samplePosts, makeConfig(), "content");
    expect(output).toContain("export interface BlogPost");
    expect(output).toContain("slug: string;");
    expect(output).toContain("featured: boolean;");
  });

  it("includes blogPosts array with correct slugs", () => {
    const output = emitDry(samplePosts, makeConfig(), "content");
    expect(output).toContain('"hello-world"');
    expect(output).toContain('"getting-started"');
    expect(output).toContain("export const blogPosts: BlogPost[]");
  });

  it("includes featuredPost export", () => {
    const output = emitDry(samplePosts, makeConfig(), "content");
    expect(output).toContain("export const featuredPost: BlogPost | null");
    expect(output).toContain("p.featured");
  });

  it("pins featuredPost by slug when config.featured is set", () => {
    const output = emitDry(samplePosts, makeConfig({ featured: "hello-world" }), "content");
    expect(output).toContain('"hello-world"');
    expect(output).toContain("p.slug ===");
  });

  it("includes allCategories and allTags exports", () => {
    const output = emitDry(samplePosts, makeConfig(), "content");
    expect(output).toContain("export const allCategories: string[]");
    expect(output).toContain("export const allTags: string[]");
    expect(output).toContain('"Engineering"');
    expect(output).toContain('"open-source"');
  });

  it("includes AUTO-GENERATED header comment", () => {
    const output = emitDry(samplePosts, makeConfig(), "content");
    expect(output).toContain("AUTO-GENERATED by mdpublish");
  });
});

describe("emitDry (JSON format)", () => {
  it("produces valid JSON with _meta, posts, allCategories, allTags", () => {
    const output = emitDry(samplePosts, makeConfig({ format: "json" }), "content");
    const parsed = JSON.parse(output) as {
      _meta: { count: number; version: string };
      posts: BlogPost[];
      allCategories: string[];
      allTags: string[];
    };

    expect(parsed._meta.count).toBe(2);
    expect(parsed._meta.version).toBe("1");
    expect(parsed.posts).toHaveLength(2);
    expect(parsed.allCategories).toContain("Engineering");
    expect(parsed.allTags).toContain("open-source");
  });
});

describe("emit (writes file)", () => {
  it("writes a TypeScript output file", () => {
    const outputPath = path.join(tmpDir, "blog.generated.ts");
    emit(samplePosts, makeConfig({ output: outputPath }), "content");

    expect(fs.existsSync(outputPath)).toBe(true);
    const content = fs.readFileSync(outputPath, "utf-8");
    expect(content).toContain("export interface BlogPost");
    expect(content).toContain("hello-world");
  });

  it("writes a JSON output file", () => {
    const outputPath = path.join(tmpDir, "blog.generated.json");
    emit(samplePosts, makeConfig({ format: "json", output: outputPath }), "content");

    expect(fs.existsSync(outputPath)).toBe(true);
    const content = fs.readFileSync(outputPath, "utf-8");
    const parsed = JSON.parse(content) as { _meta: { count: number } };
    expect(parsed._meta.count).toBe(2);
  });

  it("creates parent directories if they do not exist", () => {
    const outputPath = path.join(tmpDir, "nested", "deep", "blog.generated.ts");
    emit(samplePosts, makeConfig({ output: outputPath }), "content");
    expect(fs.existsSync(outputPath)).toBe(true);
  });
});
