export interface BlogArticle {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  tags: string[];
  author: string;
  date: string;
  readTime: string;
  views: number;
  relevance: number;
  illustrationType: "automation" | "modernization" | "integration" | "dashboard" | "architecture" | "strategy" | "mobile" | "cloud";
}

export const categories = [
  "All",
  "AI Automation",
  "Legacy Modernization",
  "Systems Integration",
  "Web & Mobile Engineering",
  "Product Strategy",
  "Architecture",
  "Case Studies",
];

export const tags = [
  "automation",
  "AI workflows",
  "migration",
  "APIs",
  "dashboards",
  "legacy systems",
  "SaaS",
  "modernization",
  "integrations",
  "cloud",
  "performance",
];

export const blogArticles: BlogArticle[] = [
  {
    id: "featured-1",
    slug: "how-to-modernize-legacy-applications",
    title: "How to Modernize Legacy Applications for AI-Era Demands",
    excerpt: "A practical guide to upgrading older systems, improving integration, and preparing your software for AI-powered workflows.",
    category: "Legacy Modernization",
    tags: ["modernization", "legacy systems", "AI workflows"],
    author: "Atlas Flow Team",
    date: "Mar 4, 2026",
    readTime: "8 min read",
    views: 4200,
    relevance: 10,
    illustrationType: "modernization",
  },
  {
    id: "article-2",
    slug: "7-signs-ready-for-ai-workflow-automation",
    title: "7 Signs Your Business Is Ready for AI Workflow Automation",
    excerpt: "Discover the key indicators that show your business is ready to automate repetitive work, reduce delays, and improve operational efficiency with AI.",
    category: "AI Automation",
    tags: ["automation", "AI workflows", "performance"],
    author: "Atlas Flow Team",
    date: "Mar 9, 2026",
    readTime: "6 min read",
    views: 3800,
    relevance: 9,
    illustrationType: "automation",
  },
  {
    id: "article-3",
    slug: "legacy-system-vs-modern-platform",
    title: "Legacy System vs Modern Platform: What Growing Businesses Need to Know",
    excerpt: "A practical comparison of legacy systems and modern platforms to help growing businesses evaluate flexibility, security, scalability, and AI readiness.",
    category: "Legacy Modernization",
    tags: ["legacy systems", "modernization", "migration"],
    author: "Atlas Flow Team",
    date: "Feb 7, 2026",
    readTime: "7 min read",
    views: 2900,
    relevance: 8,
    illustrationType: "modernization",
  },
  {
    id: "article-4",
    slug: "systems-integration-guide-growing-companies",
    title: "A Practical Guide to Systems Integration for Growing Companies",
    excerpt: "How to connect your tools, platforms, and data sources into a unified system that scales with your business.",
    category: "Systems Integration",
    tags: ["integrations", "APIs", "SaaS"],
    author: "Atlas Flow Team",
    date: "Feb 15, 2026",
    readTime: "9 min read",
    views: 3100,
    relevance: 7,
    illustrationType: "integration",
  },
  {
    id: "article-13",
    slug: "build-ai-ready-internal-tools",
    title: "How to Build AI-Ready Internal Tools Without Rebuilding Everything",
    excerpt: "Strategies for incrementally enhancing existing tools with AI capabilities while minimizing disruption.",
    category: "AI Automation",
    tags: ["automation", "AI workflows", "dashboards"],
    author: "Atlas Flow Team",
    date: "Feb 8, 2026",
    readTime: "5 min read",
    views: 1000,
    relevance: 5,
    illustrationType: "automation",
  },
  /*
  {
    id: "article-5",
    slug: "build-ai-ready-internal-tools",
    title: "How to Build AI-Ready Internal Tools Without Rebuilding Everything",
    excerpt: "Strategies for incrementally enhancing existing tools with AI capabilities while minimizing disruption.",
    category: "AI Automation",
    tags: ["automation", "AI workflows", "dashboards"],
    author: "Atlas Flow Team",
    date: "Feb 8, 2026",
    readTime: "5 min read",
    views: 2600,
    relevance: 9,
    illustrationType: "automation",
  },
  {
    id: "article-6",
    slug: "common-mistakes-software-modernization",
    title: "Common Mistakes in Software Modernization Projects",
    excerpt: "Learn from the most frequent pitfalls teams face when upgrading legacy systems and how to avoid them.",
    category: "Product Strategy",
    tags: ["modernization", "legacy systems", "performance"],
    author: "Atlas Flow Team",
    date: "Feb 1, 2026",
    readTime: "6 min read",
    views: 3400,
    relevance: 6,
    illustrationType: "strategy",
  },
  {
    id: "article-7",
    slug: "designing-operational-dashboards",
    title: "Designing Operational Dashboards That Teams Actually Use",
    excerpt: "Principles for building dashboards that drive decisions, not just display data.",
    category: "Web & Mobile Engineering",
    tags: ["dashboards", "SaaS", "performance"],
    author: "Atlas Flow Team",
    date: "Jan 25, 2026",
    readTime: "7 min read",
    views: 2200,
    relevance: 5,
    illustrationType: "dashboard",
  },
  {
    id: "article-8",
    slug: "replace-or-extend-legacy-system",
    title: "When to Replace a Legacy System and When to Extend It",
    excerpt: "A decision framework for CTOs evaluating whether to rebuild, refactor, or wrap legacy infrastructure.",
    category: "Architecture",
    tags: ["legacy systems", "migration", "cloud"],
    author: "Atlas Flow Team",
    date: "Jan 18, 2026",
    readTime: "10 min read",
    views: 1900,
    relevance: 7,
    illustrationType: "architecture",
  },
  {
    id: "article-9",
    slug: "api-integrations-reduce-manual-work",
    title: "How API Integrations Reduce Manual Work Across Teams",
    excerpt: "Real-world examples of how connecting systems through APIs eliminates repetitive tasks and accelerates workflows.",
    category: "Systems Integration",
    tags: ["APIs", "integrations", "automation"],
    author: "Atlas Flow Team",
    date: "Jan 11, 2026",
    readTime: "5 min read",
    views: 2800,
    relevance: 8,
    illustrationType: "integration",
  },
  {
    id: "article-10",
    slug: "scalable-mobile-applications-enterprise",
    title: "Building Scalable Mobile Applications for Enterprise Teams",
    excerpt: "Key architectural decisions for mobile apps that need to serve thousands of users reliably.",
    category: "Web & Mobile Engineering",
    tags: ["SaaS", "cloud", "performance"],
    author: "Atlas Flow Team",
    date: "Jan 4, 2026",
    readTime: "8 min read",
    views: 1700,
    relevance: 4,
    illustrationType: "mobile",
  },
  {
    id: "article-11",
    slug: "cloud-migration-strategies-mid-market",
    title: "Cloud Migration Strategies for Mid-Market Companies",
    excerpt: "Choosing the right cloud migration approach based on your team size, budget, and technical maturity.",
    category: "Architecture",
    tags: ["cloud", "migration", "modernization"],
    author: "Atlas Flow Team",
    date: "Dec 28, 2025",
    readTime: "9 min read",
    views: 2100,
    relevance: 6,
    illustrationType: "cloud",
  },
  {
    id: "article-12",
    slug: "manual-reporting-to-ai-driven-analytics",
    title: "From Manual Reporting to AI-Driven Analytics: A Case Study",
    excerpt: "How one mid-market company cut reporting time by 80% through AI-powered data pipelines.",
    category: "Case Studies",
    tags: ["automation", "AI workflows", "dashboards"],
    author: "Atlas Flow Team",
    date: "Dec 20, 2025",
    readTime: "6 min read",
    views: 3600,
    relevance: 10,
    illustrationType: "automation",
  },
  */
];
