import fs from "fs";
import path from "path";
import type { BlogPost, ResolvedConfig } from "../types.js";

const HEADER_COMMENT = `// AUTO-GENERATED by mdpublish — do not edit manually
// Run \`npx mdpublish sync\` to regenerate`;

function formatDate(): string {
  return new Date().toISOString();
}

function serializeString(value: string): string {
  return JSON.stringify(value);
}

function serializeStringArray(values: string[]): string {
  return `[${values.map(serializeString).join(", ")}]`;
}

function serializePost(post: BlogPost): string {
  const lines = [
    `  {`,
    `    slug: ${serializeString(post.slug)},`,
    `    title: ${serializeString(post.title)},`,
    `    excerpt: ${serializeString(post.excerpt)},`,
    `    category: ${serializeString(post.category)},`,
    `    tags: ${serializeStringArray(post.tags)},`,
    `    author: ${serializeString(post.author)},`,
    `    date: ${serializeString(post.date)},`,
    `    readTime: ${serializeString(post.readTime)},`,
    `    featured: ${post.featured},`,
    `    draft: ${post.draft},`,
    `    order: ${post.order ?? 0},`,
    `  }`,
  ];
  return lines.join("\n");
}

function buildTypescriptOutput(
  posts: BlogPost[],
  contentDir: string,
  config: ResolvedConfig
): string {
  const allCategories = [...new Set(posts.map((p) => p.category))].sort();
  const allTags = [...new Set(posts.flatMap((p) => p.tags))].sort();

  const featuredSlug = config.featured;
  const featuredExpr = featuredSlug
    ? `blogPosts.find((p) => p.slug === ${serializeString(featuredSlug)}) ?? null`
    : `blogPosts.find((p) => p.featured) ?? null`;

  const postLiterals = posts.map(serializePost).join(",\n");
  const categoriesLiteral = allCategories.map((c) => `  ${serializeString(c)}`).join(",\n");
  const tagsLiteral = allTags.map((t) => `  ${serializeString(t)}`).join(",\n");

  return [
    HEADER_COMMENT,
    `// Source: ${contentDir}  |  Generated: ${formatDate()}`,
    ``,
    `export interface BlogPost {`,
    `  slug: string;`,
    `  title: string;`,
    `  excerpt: string;`,
    `  category: string;`,
    `  tags: string[];`,
    `  author: string;`,
    `  date: string;`,
    `  readTime: string;`,
    `  featured: boolean;`,
    `  draft: boolean;`,
    `  order: number;`,
    `}`,
    ``,
    `export const blogPosts: BlogPost[] = [`,
    postLiterals,
    `];`,
    ``,
    `export const featuredPost: BlogPost | null =`,
    `  ${featuredExpr};`,
    ``,
    `export const allCategories: string[] = [`,
    categoriesLiteral,
    `];`,
    ``,
    `export const allTags: string[] = [`,
    tagsLiteral,
    `];`,
    ``,
  ].join("\n");
}

function buildJsonOutput(
  posts: BlogPost[],
  contentDir: string
): string {
  const allCategories = [...new Set(posts.map((p) => p.category))].sort();
  const allTags = [...new Set(posts.flatMap((p) => p.tags))].sort();

  const output = {
    _meta: {
      generated: formatDate(),
      version: "1",
      count: posts.length,
      source: contentDir,
    },
    posts,
    allCategories,
    allTags,
  };

  return JSON.stringify(output, null, 2) + "\n";
}

/**
 * Writes the generated output file.
 * Creates parent directories if they don't exist.
 */
export function emit(
  posts: BlogPost[],
  config: ResolvedConfig,
  contentDir: string
): void {
  const outputPath = path.resolve(config.output);
  const outputDir = path.dirname(outputPath);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const content =
    config.format === "json"
      ? buildJsonOutput(posts, contentDir)
      : buildTypescriptOutput(posts, contentDir, config);

  fs.writeFileSync(outputPath, content, "utf-8");
}

/**
 * Returns the generated output as a string without writing to disk.
 * Used for --dry-run mode.
 */
export function emitDry(
  posts: BlogPost[],
  config: ResolvedConfig,
  contentDir: string
): string {
  return config.format === "json"
    ? buildJsonOutput(posts, contentDir)
    : buildTypescriptOutput(posts, contentDir, config);
}
